# Generated by Django 3.1.6 on 2021-06-15 18:33

from django.db import migrations, models
import django.db.models.deletion
import game.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Box",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.UUIDField(default=uuid.uuid4, verbose_name="Card UUID")),
                (
                    "suit",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Spades"),
                            (2, "Diamonds"),
                            (3, "Clubs"),
                            (4, "HEARTS"),
                        ],
                        verbose_name="Card suit",
                    ),
                ),
                (
                    "value",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "card_Ace"),
                            (13, "card_King"),
                            (12, "card_Queen"),
                            (11, "card_Jack"),
                            (2, "card_2"),
                            (3, "card_3"),
                            (4, "card_4"),
                            (5, "card_5"),
                            (6, "card_6"),
                            (7, "card_7"),
                            (8, "card_8"),
                            (9, "card_9"),
                            (10, "card_10"),
                        ],
                        verbose_name="Card value",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
            ],
            options={
                "verbose_name": "Card",
                "verbose_name_plural": "Cards",
            },
        ),
        migrations.CreateModel(
            name="Deck",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                ("uid", models.UUIDField(default=uuid.uuid4, verbose_name="Deck UUID")),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Deck title",
                    ),
                ),
                (
                    "cong_text",
                    models.TextField(
                        blank=True,
                        default="",
                        max_length=1000,
                        verbose_name="Congratulation text",
                    ),
                ),
                (
                    "uploaded",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Deck uploaded"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Deck updated"),
                ),
                (
                    "pin",
                    models.CharField(
                        blank=True, max_length=4, null=True, verbose_name="Deck PIN"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Active")),
                ("expires", models.DateTimeField(verbose_name="Date expire")),
                (
                    "mirror",
                    models.BooleanField(
                        default=True, null=True, verbose_name="Mirror ON"
                    ),
                ),
                (
                    "demo_mobile",
                    models.BooleanField(default=False, verbose_name="For mobile apps"),
                ),
            ],
            options={
                "verbose_name": "Deck",
                "verbose_name_plural": "Decks",
            },
        ),
        migrations.CreateModel(
            name="DeckFace",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.UUIDField(default=uuid.uuid4, verbose_name="Face uid")),
                ("title", models.TextField(blank=True, verbose_name="Title")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Last update"),
                ),
                (
                    "json_settings",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Json settings"
                    ),
                ),
                (
                    "md5",
                    models.CharField(
                        blank=True, default="", editable=False, max_length=150
                    ),
                ),
            ],
            options={
                "verbose_name": "Deck face style",
                "verbose_name_plural": "Deck face styles",
            },
        ),
        migrations.CreateModel(
            name="DeckFacesJsonSchema",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("json", models.JSONField(verbose_name="JSON Validation schema")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DeckShirt",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.UUIDField(default=uuid.uuid4, verbose_name="Shirt uid")),
                ("title", models.TextField(blank=True, verbose_name="Title")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Last update"),
                ),
                (
                    "border_color",
                    models.CharField(
                        blank=True,
                        default="0D5822",
                        max_length=10,
                        verbose_name="Border color",
                    ),
                ),
            ],
            options={
                "verbose_name": "Deck shirt",
                "verbose_name_plural": "Deck shirts",
            },
        ),
        migrations.CreateModel(
            name="ImageCollection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "img",
                    models.ImageField(
                        null=True,
                        upload_to=game.utils.user_deck_path,
                        verbose_name="Image",
                    ),
                ),
                ("md5", models.CharField(editable=False, max_length=150)),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="game.imagecollection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Image",
                "verbose_name_plural": "Images",
            },
        ),
        migrations.CreateModel(
            name="GameScore",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.PositiveSmallIntegerField(verbose_name="Game score")),
                ("time", models.DurationField(verbose_name="Played time")),
                (
                    "won",
                    models.BooleanField(default=False, verbose_name="Won the game"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Score created"
                    ),
                ),
                ("ip", models.CharField(max_length=50, verbose_name="IP of player")),
                (
                    "deck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games",
                        to="game.deck",
                        verbose_name="played with deck",
                    ),
                ),
            ],
            options={
                "verbose_name": "Game score",
                "verbose_name_plural": "Game scores",
            },
        ),
    ]
