# Generated by Django 3.1.6 on 2021-06-15 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("game", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamescore",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="played_games",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Player",
            ),
        ),
        migrations.AddField(
            model_name="deckshirt",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shirt",
                to="game.image",
                verbose_name="Shirt image",
            ),
        ),
        migrations.AddField(
            model_name="deckface",
            name="images",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="model",
                to="game.imagecollection",
                verbose_name="Face images collection",
            ),
        ),
        migrations.AddField(
            model_name="deck",
            name="box",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="game.box",
                verbose_name="Deck box",
            ),
        ),
        migrations.AddField(
            model_name="deck",
            name="face",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="game.deckface",
                verbose_name="Face",
            ),
        ),
        migrations.AddField(
            model_name="deck",
            name="shirt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="game.deckshirt",
                verbose_name="Shirt",
            ),
        ),
        migrations.AddField(
            model_name="deck",
            name="transaction",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="orders.transaction",
                verbose_name="Transaction",
            ),
        ),
        migrations.AddField(
            model_name="deck",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="decks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="deck",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cards",
                to="game.deck",
                verbose_name="Deck",
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="image",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="game.image",
                verbose_name="Image",
            ),
        ),
        migrations.AddField(
            model_name="box",
            name="image",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="game.image",
                verbose_name="Image",
            ),
        ),
    ]
