# Generated by Django 3.1.13 on 2022-04-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_deck_cong_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="decktranslate",
            name="date_updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Date updated"),
        ),
    ]
