# Generated by Django 3.1.13 on 2021-10-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0002_auto_20210615_2133"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deckaccesslog",
            name="created",
            field=models.DateTimeField(auto_now=True, verbose_name="Recorded"),
        ),
    ]
