# Generated by Django 3.1.6 on 2021-06-15 18:33

from django.db import migrations, models
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Feedback")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Answered"),
                ),
                ("new", models.BooleanField(default=True, verbose_name="New")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("answer", models.TextField(blank=True, verbose_name="Answer")),
            ],
            options={
                "ordering": ["user", "-created"],
            },
        ),
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    shortuuidfield.fields.ShortUUIDField(
                        blank=True, editable=False, max_length=22, unique=True
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start promo date")),
                ("end_date", models.DateField(verbose_name="End promo date")),
                (
                    "limit",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Limit of the usage"
                    ),
                ),
                (
                    "discount",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="Discount for the promo"
                    ),
                ),
                (
                    "counter",
                    models.PositiveSmallIntegerField(
                        default=0, editable=False, verbose_name="Usage counter"
                    ),
                ),
            ],
        ),
    ]
