# Generated by Django 3.1.6 on 2021-06-15 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrintLayout",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        null=True, upload_to="", verbose_name="Print layout"
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("counter", models.IntegerField(default=0, verbose_name="counter")),
                ("task", models.CharField(max_length=50, verbose_name="Task")),
                (
                    "deck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game.deck",
                        verbose_name="Deck",
                    ),
                ),
            ],
            options={
                "verbose_name": "Print layout",
                "verbose_name_plural": "Print layouts",
            },
        ),
    ]
